name: dog-breed-classifier-webservice-env
dependencies:
  - conda=4.10.*
  - python=3.9.*
  - pip=21.2.*
  - pip:
    - --extra-index-url https://test.pypi.org/simple/ 
    - dog_breed_classifier==0.0.9
    - flask==2.0.*
    - flask-restx==0.5.*
    - Flask-WTF==1.0.*
    - Flask-Reuploaded==1.2.*
    - pylint==2.10.*
